
language: node_js

node_js: 
  - "node"
cache:
  directories:
    - "node_modules"
  env:
    global:
    - CC_TEST_REPORTER_ID=f68cf4cc089210f61efa330a4d62926bd057285ed0a8d95cac91061091217f8f

before_script:
  - npm install
  - npm install -g coveralls
  - npm install -g nyc
  - curl -L https://codeclimate.com/downloads/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: 
  - npm run test
after_success:
  - npm run coveralls
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
