
language: node_js

node_js: 
  - "8.9.4"
cache:
  directories:
    - "node_modules"

before_script:
  - npm install
  - npm install -g nyc
  - npm install -g babel-cli
  - npm install -g coveralls

script:
  - nyc --reporter=lcov npm run test

after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT