language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install
  - npm install coveralls

script: "npm run-script cover"

install: "install: travis_wait 30 mvn install"

after-script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

after_succeess:
  - npm run coveralls
