language: node_js

node_js: 
  - "8.9.4"
cache:
  directories:
    - "node_modules"
 after_script:
    - npm run coveralls

before_script:
  - npm install
  - npm install coveralls

script: 
  - npm run test

