language: node_js

node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"

before_script:
  - npm install
  - npm install coveralls

script: 
  - npm run-script test


after_succeess:
  - npm run coveralls

deploy: 
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  all_branches: true

