language: node_js

node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"

before_script:
  - npm install
  - npm install coveralls

script: 
  - npm run-script cover --watch=false

after-script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"

after_succeess:
  - npm run coveralls

deploy: 
  skip-cleanup: true
  github-token: $GITHUB_TOKEN

