language: node_js

node_js: 
  - "node"
cache:
  directories:
    - "node_modules"
 after_script:
    - npm run coveralls

before_script:
  - npm install
  - npm install coveralls

script: 
  - npm run test
after_success:
  - npm run coveralls
  -  after-build --exit-code 
